name: 构建Tauri应用

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 安装Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装依赖
        run: pnpm install

      - name: 构建Next.js应用
        run: pnpm --filter @zhilian/web build
        
      - name: 构建Tauri应用
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/desktop
          tagName: v__VERSION__
          releaseName: '智链安全平台 v__VERSION__'
          releaseBody: |
            智链网络安全分析溯源平台 Windows版本
            
            ## 安装说明
            1. 下载 `.msi` 安装包
            2. 双击安装包
            3. 按照向导完成安装
            4. 在桌面或开始菜单找到"智链安全平台"启动应用
            
            ## 特性
            - ✅ 真实中国地图流量态势展示
            - ✅ 实时网络流量监控
            - ✅ 威胁告警系统
            - ✅ 规则管理功能
            - ✅ 主机性能监控
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true

      - name: 上传安装包
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            apps/desktop/src-tauri/target/release/bundle/msi/*.msi
            apps/desktop/src-tauri/target/release/bundle/nsis/*.exe
